# Generated by Django 4.2.5 on 2023-10-22 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payment.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(auto_now_add=True, verbose_name='дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('card', 'картой'), ('cash', 'наличными')], default='cash', max_length=100, verbose_name='способ оплаты')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('content_type', models.ForeignKey(default=payment.models.get_default_content_type, limit_choices_to=models.Q(models.Q(('app_label', 'training_courses'), ('model', 'course')), models.Q(('app_label', 'training_courses'), ('model', 'lesson')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('content_type', models.ForeignKey(default=payment.models.get_default_content_type, limit_choices_to=models.Q(models.Q(('app_label', 'training_courses'), ('model', 'course')), models.Q(('app_label', 'training_courses'), ('model', 'lesson')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment', verbose_name='платеж')),
            ],
            options={
                'verbose_name': 'сессия оплаты Stripe',
                'verbose_name_plural': 'сессии оплаты Stripe',
            },
        ),
    ]
