# Generated by Django 4.2.5 on 2023-10-18 16:00

from django.db import migrations, models
import django.db.models.deletion
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0002_remove_payment_course_remove_payment_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(default=payment.models.get_default_content_type, limit_choices_to=models.Q(models.Q(('app_label', 'training_courses'), ('model', 'course')), models.Q(('app_label', 'training_courses'), ('model', 'lesson')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='content_type',
            field=models.ForeignKey(default=payment.models.get_default_content_type, limit_choices_to=models.Q(models.Q(('app_label', 'training_courses'), ('model', 'course')), models.Q(('app_label', 'training_courses'), ('model', 'lesson')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
