# Generated by Django 4.2.5 on 2023-10-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
    ]
