# Generated by Django 4.2.5 on 2023-10-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=100, verbose_name='название курса')),
                ('preview_img_course', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='превью курса')),
                ('description_course', models.TextField(verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=100, verbose_name='название урока')),
                ('description_lesson', models.TextField(verbose_name='описание урока')),
                ('preview_img_lesson', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='превью урока')),
                ('video_url_lesson', models.TextField(blank=True, null=True, verbose_name='url_видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_courses.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
