# Generated by Django 4.2.5 on 2023-10-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_courses', '0002_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url_lesson',
            field=models.URLField(blank=True, null=True, verbose_name='url_видео'),
        ),
    ]
